[FABCN-388] Tutorial updated
hyperledger/fabric-chaincode-node pull request #246
Opened 2020-12-08 12:35 UTC by kemi04

Signed-off-by: Kestutis Gudynas <44440041+kemi04@users.noreply.github.com>

2020-12-08 13:36 UTC, mbwhite requested changes

2020-12-08 13:36 UTC, mbwhite commented on docs/_jsdoc/tutorials/using-typescript-decorators.md
> +**Note that emitDecoratorMetadata property in *tscondig.json* file is mandatory.**
tsconfig...

2020-12-08 13:44 UTC, kemi04 commented on docs/_jsdoc/tutorials/using-typescript-decorators.md
> +**Note that emitDecoratorMetadata property in *tscondig.json* file is mandatory.**
Thank you. Fixed it.

2020-12-09 11:29 UTC, mbwhite approved these changes

2020-12-09 11:29 UTC, merged